Algoritmo "contadorPara"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/02/2021
Var
// Seção de Declarações das variáveis
   c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    para c <- 10 ate 0 passo - 1 faca
         escreval (c)
    fimpara
Fimalgoritmo